### ISSUE TITLE
Fatal error: Uncaught TelegramBot\TelegramException: [400]: Bad Request: group chat was upgraded to a supergroup chat   thrown in /vendor/lukasss93/telegrambot-php/src/TelegramBot.php on line 2082

### ISSUE THREAD

**Issue by Megachip** [Lukasss93/telegrambot-php#6]
Looks like after a 3rd person joined the Channel, the ID changed. After using the new ID I'll get the following error:
```
Fatal error: Uncaught TelegramBot\TelegramException: [400]: Bad Request: chat not found
  thrown in /vendor/lukasss93/telegrambot-php/src/TelegramBot.php on line 2082
```

**Comment by Lukasss93** [comment]
Hi! Send me more informations about how to replicate this and/or a sample code you used for.

**Comment by Megachip** [comment]
@Lukasss93 thanks for your quick response, but issue was on Telegram side ;) Which changing the visibility of the older messages, the group was migrated to an supergroup which gets an new id which have to staring with -100 (instead of -)
